/**
 * CSS selectors for content extraction
 */

export const contentSelectors = [
  // Wikipedia-specific selectors (highest priority)
  '#mw-content-text .mw-parser-output',
  '#mw-content-text',
  '.mw-parser-output',

  // High-priority content selectors
  "main:not([class*='nav']):not([class*='menu']):not([class*='sidebar'])",
  "article:not([class*='related']):not([class*='recommended'])",
  '[role="main"]:not([class*="sidebar"])',
  '.content:not(.sidebar):not(.nav):not(.menu)',
  '.main-content:not(.sidebar)',
  '.post-content:not(.meta):not(.author)',
  '.entry-content:not(.sidebar)',
  '.article-content:not(.related)',
  '.article-body:not(.sidebar)',
  '.story-body:not(.related)',
  '.text-content:not(.sidebar)',
  "[data-testid='article-body']",
  '.prose:not(.sidebar)',
  // Medium-priority selectors
  '.container main',
  '.wrapper article',
  '#main-content',
  '#content:not(.sidebar)',
  '.page-content:not(.sidebar)',
  '.blog-content:not(.sidebar)',
  // Lower priority but common patterns
  '.single-post .content',
  '.post .entry',
  '.article .body',
  // Last resort - but exclude obvious non-content
  'body',
];

export const excludeSelectors = [
  'nav',
  'header',
  'footer',
  'aside',
  '.sidebar',
  '.nav',
  '.menu',
  '.breadcrumb',
  '.pagination',
  '.related',
  '.recommended',
  '.comments',
  '.comment',
  '.social',
  '.share',
  '.tags',
  '.author-bio',
  '.author-info',
  '.meta',
  '.metadata',
  '.advertisement',
  '.ads',
  '.ad',
  '.sponsor',
  '.promo',
  '.newsletter',
  '.subscribe',
  '.signup',
  '.login',
  '.search',
  '.filter',
  '.sort',
  "[role='complementary']",
  '.widget',
  '.banner',
  '.alert',
  '.notice',
  '.popup',
  '.cookie',
  '.gdpr',
  '.privacy',
  '.legal',
  '.disclaimer',
  'script',
  'style',
  'noscript',
  // Wikipedia-specific excludes (add the most problematic ones but keep navigation boxes)
  '#siteNotice',
  '.printfooter',
  '.catlinks',
  '#footer',
  '.mw-editsection',
];
